// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Fable.ReactTestingLibrary")>]
[<assembly: AssemblyProductAttribute("Fable.Jester")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings for jest and friends")>]
[<assembly: AssemblyVersionAttribute("0.16.0")>]
[<assembly: AssemblyFileVersionAttribute("0.16.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Fable.ReactTestingLibrary.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.ReactTestingLibrary"
    let [<Literal>] AssemblyProduct = "Fable.Jester"
    let [<Literal>] AssemblyDescription = "Fable bindings for jest and friends"
    let [<Literal>] AssemblyVersion = "0.16.0"
    let [<Literal>] AssemblyFileVersion = "0.16.0"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Fable.ReactTestingLibrary.Tests"
